CREATE DATABASE DQL334;
USE DQL334;

#DQL-----> DATA QUERY LANGUAGE-----> FETCHING THE DATA
#FILTERING, SORTING, GROUPING, USING FUNCTIONS TO RETRIVE THE DATA
#DQL IS MOST IMPORTANT LANGUAGE FOR DATA ANALYSTS
#CHECK DATA IN ALL THE TABLES 
SELECT * FROM ORDERDETAILS;
SELECT * FROM ORDERS;
SELECT * FROM PAYMENTS;
SELECT * FROM PRODUCTLINES;
SELECT * FROM PRODUCTS;
SELECT * FROM CUSTOMERS;
SELECT * FROM EMPLOYEES;
SELECT * FROM OFFICES;

#SELECT-----> GIVES YOU DATA ACCORDING TO YOUR REQUIREMENT

#TO FETCH SPECIFIC COLUMNS DATA

SELECT EMPLOYEENUMBER, FIRSTNAME, OFFICECODE FROM EMPLOYEES;

#TO FETCH SPECIFIC CO;UMNS WITH TEMPORARY NAME
SELECT * FROM CUSTOMERS;

SELECT CUSTOMERNUMBER "ID", CONTACTFIRSTNAME "FIRSTNAME", CREDITLIMIT FROM CUSTOMERS;

#TO CHECK UNIQUE VALUES FROM PARTICULAR COLUMN

#SELECT DISTINCT COUNTRY, CUSTOMERNAME FROM CUSTOMERS; THE ABOVE COMMAND IS WRONG
#YOU CANNOT USE DISTINCT KEYWORD WITH MORE THAN ONE COLUMN THEREFORE ABOVE IS WRONG


#FILTERING THE ROW DATA
#FILTER DATA OF CUSTOMERS HAVING CREDITLIMIT MORE THAN 20000
SELECT CUSTOMERNUMBER, CUSTOMERNAME, CREDITLIMIT FROM CUSTOMERS WHERE CREDITLIMIT>=20000;

#FILTER ALL TE CUSTOMERS FROM USA AND FRANCE

SELECT CUSTOMERNUMBER, CUSTOMERNAME, COUNTRY FROM CUSTOMERS WHERE COUNTRY="USA";
SELECT CUSTOMERNUMBER, CUSTOMERNAME, COUNTRY FROM CUSTOMERS WHERE COUNTRY="USA" OR COUNTRY= "FRANCE";
SELECT CUSTOMERNUMBER, CUSTOMERNAME, COUNTRY FROM CUSTOMERS WHERE COUNTRY
IN("USA","UK","GERMANY","FRANCE");
SELECT CUSTOMERNUMBER, CUSTOMERNAME, CREDITLIMIT FROM CUSTOMERS WHERE CREDITLIMIT BETWEEN 20000 AND 100000;

SELECT EMPLOYEENUMBER, FIRSTNAME, LASTNAME, OFFICECODE FROM EMPLOYEES WHERE OFFICECODE BETWEEN 1 AND 4;

SELECT CUSTOMERNUMBER, CUSTOMERNAME, COUNTRY FROM CUSTOMERS
WHERE COUNTRY!="AUSTRALIA";  

#FETCH EMPLOYEES WORKING IN OFFICECODE 2,4,7,5
SELECT EMPLOYEENUMBER, FIRSTNAME, LASTNAME, OFFICECODE FROM EMPLOYEES WHERE OFFICECODE IN(2,4,5,7);

#FETCH CUSTOMERS NOT STAYING IN USA, UK, GERMANY
SELECT CUSTOMERNUMBER, CUSTOMERNAME, COUNTRY FROM CUSTOMERS
WHERE NOT COUNTRY IN("USA", "UK", "GERMANY");

#LIKE OPERATOR -----> TRIES TO MATCH THE PATTERN
#WILDCARD SYMBOLS------>1) % -----> MULTIPLE CHARACTER, 2) _--------> SINGLE CHARACTER 

#FIND ALL THE EMPLOYEES WHOSE LAST NAME STARTS WITH "P"

SELECT * FROM EMPLOYEE;
SELECT EMPLOYEENUMBER, FIRSTNAME, LASTNAME FROM EMPLOYEES
WHERE LASTNAME LIKE"P%";

#FIND ALL THE EMPLOYEES WHOSE LAST NAME START WITH "Y"

SELECT EMPLOYEENUMBER, FIRSTNAME, LASTNAME FROM EMPLOYEES
WHERE FIRSTNAME LIKE"%Y";

#FIND ALL THE EMPLOYEES WHO HAVE "O" IN SECOND CHARACTER
SELECT EMPLOYEENUMBER, FIRSTNAME, LASTNAME FROM EMPLOYEES
WHERE LASTNAME LIKE"_O%";

#FETCH ALL THE PRODUCTS WHOSE PRODUCT LINE HAS "S" AS THE 4TH CHARACTER
SELECT * FROM PRODUCTLINES;
SELECT PRODUCTLINE, PRODUCTCODE, PRODUCTNAME FROM PRODUCTS WHERE PRODUCTLINE LIKE "___S%";
#ISNULL OPERATOR
#FETCH THE CUSTOMERS DATA WHERE STATE IS BLANK(NULL)

SELECT CUSTOMERNUMBER, CUSTOMERNAME, STATE, COUNTRY FROM CUSTOMERS
WHERE STATE IS NULL;

#UPDATE STATE AS GRAND EST WHERE COUNTRY IS FRANCE & STATE IS BLANK(NULL)
UPDATE CUSTOMERS SET STATE="GRAND. EST"
WHERE STATE IS NULL AND COUNTRY="FRANCE";
set sql_safe_updates=0;

#SORT THE DATA OF CUSTOMERS COUNTRYWISE
SELECT * FROM CUSTOMERS;

#ORDER BY CLAUSE ----> SORT YOUR DATA
SELECT CUSTOMERNUMBER, CUSTOMERNAME, COUNTRY FROM CUSTOMERS
ORDER BY COUNTRY;

#SAME IN DESCENDING ORDER
SELECT CUSTOMERNUMBER, CUSTOMERNAME, COUNTRY FROM CUSTOMERS
ORDER BY COUNTRY DESC;

 #ORDER BY ON MULTIPLE COLMNS
 SELECT * FROM EMPLOYEES;
 
 SELECT EMPLOYEENUMBER, FIRSTNAME , OFFICECODE FROM EMPLOYEES
 ORDER BY OFFICECODE, FIRSTNAME DESC;
 
 #SORT THE CUSTOMERS DATA CREDITLIMITWISE
  SELECT CUSTOMERNUMBER, CUSTOMERNAME , COUNTRY FROM CUSTOMERS
 ORDER BY CREDITLIMIT DESC;
 
 # #SORT THE CUSTOMERS DATA CREDITLIMITWISE BUT ONLY FOR USA UK FRANCE
 SELECT CUSTOMERNUMBER, CUSTOMERNAME , COUNTRY, CREDITLIMIT FROM CUSTOMERS
WHERE COUNTRY IN("USA","UK","FRANCE")
ORDER BY CREDITLIMIT DESC;

#LIMIT CLAUSE

#TOP 10 CUSTOMERS WITH HIGHEST CREDITLIMIT
SELECT CUSTOMERNUMBER, CUSTOMERNAME, CREDITLIMIT, COUNTRY FROM CUSTOMERS
ORDER BY CREDITLIMIT DESC
LIMIT 10;

#BOTTOM 20 CUSTOMERS WITH LOWEST CRDITLIMIT
SELECT CUSTOMERNUMBER, CUSTOMERNAME, CREDITLIMIT, COUNTRY FROM CUSTOMERS
ORDER BY CREDITLIMIT
LIMIT 20;

#FETCH THE CUSTOMER WHO IS AT 3RD RANK CREDITLIMIT WISE
SELECT CUSTOMERNUMBER, CUSTOMERNAME, CREDITLIMIT, COUNTRY FROM CUSTOMERS
ORDER BY CREDITLIMIT DESC
LIMIT 1
OFFSET 2;

SELECT CUSTOMERNUMBER, CUSTOMERNAME, CREDITLIMIT, COUNTRY FROM CUSTOMERS
ORDER BY CREDITLIMIT DESC
LIMIT 3;#CROSS VERIFY.

#FETCH THE 1ST & 3RD HIGHEST AMOUNT PAID
select * from payments 
order by amount desc
limit 2
offset 0;

select * from payments 
order by amount desc
limit 2
offset 1;

#GROUP BY CLAUSE--> Group by clause can be applied by category column,not on numerical coloumn
#It will always be used with aggregate functions
#To filter the data by group by we will use having clause
#having clause--> or conditions--> in operations
#GHOL-->Group by, having, order, limit-->grouping, filtering, sorting, limit

#sum-->aggregate functions

#total creditlimit countrywise
select country, sum(creditlimit) "Total CL" from customers group by country;

select distinct country from customers;

#Fetch total paid by each customer
select sum(amount) "TOtal Paid", customernumber from payments group by customernumber;

#Fetch the first customer countrywise with highest creditlimit
select country, customernumber, customername, max(creditlimit) "Highest CL" from customers group by country order by creditlimit desc;

#find average CL of australia, usa, france and germany and list them from highest to lowest
select country, avg(creditlimit) "AVERAGE CL" from customers group by country having country in("Australia", "USA", "France", "Germany") order
 by avg(creditlimit) desc;

#find average CL of australia, usa, france and germany and fetch the highest from all the 4 countries
select country, avg(creditlimit) "AVERAGE CL" from customers group by country having country in("Australia", "USA", "France", "Germany") order
 by avg(creditlimit) desc limit 1;

#count the employees in each office and sort the office data from highest to lowest employee count
select officecode, count(employeenumber) from employees group by officecode order by count(employeenumber) desc;

#CASE CLAUSE-->ADDITIONAL COLUMN for o/p
#FRANCE-->5% discount
#USA-->2% discount
#Australia--> 1% discount
#other countries--> no discount
select customernumber, customername, country, case country when "France" then "5%" when "USA" then "2%" when "Australia" 
then "1%" else "no discount" end "Discount" from customers;

alter table customers add column discount varchar(15) after country;
update customers set discount=
case country when "France" then "5%" when "USA" then "2%" when "Australia" 
then "1%" else "no discount" end;

set sql_safe_updates=0;
